### ISSUE TITLE
use smaller data set for development

### ISSUE THREAD

**Issue by tcatapano** [cul/fabl#5]
Since the reindexing takes so long, maybe we should switch to a random sample of EAD (20% of each repo) for the time being? There doesnt seem to be much value in dealing with such a large test body.

**Comment by marquis** [comment]
Doesn't really matter to me.
It's nice to see how the full set looks - e.g., to understand how
significantly the subcompontent splitting inflates the facet value counts.
And as I develop these rules I'm doing selective single-file re-indexing to
verify my result, before turning loose on the full set.
In fact, I might kind of want to process the full set to see how effective
my total cleanup work goes, and get a true scale of what's left over.
I'd say save some work and leave it as it is.

**Comment by tcatapano** [comment]
OK. Sounds good.
